version: 2
updates:
#  - package-ecosystem: "gradle"
#    directory: "/"
#    schedule:
#      interval: "monthly"

#  - package-ecosystem: "npm"
#    directory: "/webstart-infrastructure/"
#    schedule:
#      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
