dist: xenial
language: java
sudo: false

before_script:
  # Required for sonar to provide blame information
  - git fetch --unshallow

script:
  - ./gradlew clean check sonarqube jacocoTestReport --info --stacktrace

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.sonar/cache/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  sonarcloud:
    organization: "itsallcode"
    token:
      secure: "rE39MoO0r69DSneQlvfOmxPLJ6ZUqvob3sr1FcRhEuxbpt1Ifv+mcoYKMv78W+3Qqcb3Tga37NoDlPOQItoO/Qmd6z5Jx6ugqNQCJNW7IIdv4AVyxi9zeWx3jwlVdwqJMtsmdHB7T6q8xBS9BPKk91kVz4hT+4Hn1ohvQLa6x4Vuz/SYsytMRNGuZnJieuqlWMF0CN36gmIlvJJmG6ZVrcy6LGRRyypqnUc57kTeIIsnl7KmHShMmUqFTrcFNz+xUhqHKPdMX1k2arE6IQ1aBEEQtJQTvF0wBO6JbFcjYYRgZ/A51WCeCQjwIo5I3m+GGtpZlrLvS021RD8FgZrsW6LslDAagmWt/bmOkIOZDNrtTZtwGDodJj1zWXJGT94gb7Iuhmc4rseP+GVQ49eQ7F7B5TPfxNx5GPj/Xc9TyIj7WZ6Xp+z9LZSV7fdF8Rti6GfTjVKwO8WUJOWSKjHPVveMNDaxR0sMgWXykn9ZhLyHwnPXk/OwYfEFito6/J9xlE+40HKAPvhwNXrcH/52SL1MN+Ea/b7G2wQiYYK1ePhRHgbhOL+ES07o63+WfOr0hBPcauudBNZKB6NdnDnYTwk5M78iXQx/BQ2qgzjIFExhzzrKwaKGfghnxm+qN/NX57o5p5qbHT354nbFw9xBm8dQaORlq16nkbodrz0MUCw="
