name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: gradle/wrapper-validation-action@v1
    - name: Cache Gradle packages and wrapper
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: |
        ./gradlew build --info --stacktrace --warning-mode=summary
    - name: Sonar analysis
      run: |
        ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io \
                            -Dsonar.organization=itsallcode \
                            -Dsonar.login=$SONAR_TOKEN \
                            --info --stacktrace --warning-mode=summary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: develop
        # Already checked via Eclipse code formatter and Sonar
        VALIDATE_JAVA: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Archive jfxui binary
      uses: actions/upload-artifact@v1
      with:
        name: jfxui
        path: jfxui/build/libs/jfxui-all.jar
    - name: Archive textui binary
      uses: actions/upload-artifact@v1
      with:
        name: textui
        path: textui/build/libs/textui-all.jar
