name: Build Infrastructure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Cache npm files
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-
    - name: Configure webstart
      run: |
        cp .github/workflows/webstart.properties.template webstart/webstart.properties
        cp .github/workflows/infrastructure-config.ts.template webstart-infrastructure/config.ts

    - name: Build webstart infrastructure
      run: |
        cd webstart-infrastructure
        npm ci
        npm run build
        npm run cdk synth
